version: '3.8'

services:
  server:
    build:
      context: ./backend   # Path to the backend directory
      dockerfile: Dockerfile
    image: server-side
    container_name: backend-server
    command: node app.js
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://leafadmin:leaf123@leafy.gnw7mw8.mongodb.net/leafCollection
      - JWT_SECRET=9B2F3C4E1A6D8F0B5E7A2C4D9F1E3B8A7D6F4C3E8A2B1C7D4F8E2A6B3C1D9F2
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-client
    ports:
      - "5173:5173"  # Ensure the port mapping matches the serve command
    networks:
      - app-network

volumes:
  backend_node_modules:
    driver: local

networks:
  app-network:
    driver: bridge