version: '3.8'

services:
  server:
    build:
      context: ./backend   # Path to the backend directory
      dockerfile: Dockerfile
    image: server-side
    container_name: backend-server
    command: npm start
    volumes:
      - ./backend:/usr/src/app   # Mount the backend directory to /usr/src/app in the container
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://leafadmin:leaf123@leafy.gnw7mw8.mongodb.net/leafCollection
    networks:
      - app-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-client
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  frontend_node_modules:
    driver: local


networks:
  app-network:
    driver: bridge
